language: node_js
node_js: 8
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build

deploy:
  provider: firebase
  project: "comments-downloader"
  token: "$FIREBASE_TOKEN"
  skip_cleanup: true
  on:
    tags: true
